version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: library-mysql
    environment:
      MYSQL_ROOT_PASSWORD: junrey123
      MYSQL_DATABASE: library_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - 3307:3306 # Change 3307 to any other unused port
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
